### ISSUE TITLE
Allow to override property schema "readOnly" and "description" in swagger_context

### ISSUE THREAD

**Issue by piotrbrzezina** [api-platform/core#2133]
Hi 

I'm currently trying to use API platform with DTO instead of Entity but I have a small issue with documentation.  My DTO set all data by constructor and property are privet so in the documentation I do not see them because those params are marks as read-only and I can`t find how to override that. 

example
```
/**
 * @ApiResource(
 *      collectionOperations={
 *          "post"={"method"="POST", "path"="/login"}
 *      },
 *      itemOperations={}
 *  )
 */
class Login
{
/**
 * @ApiResource(
 *      collectionOperations={
 *          "post"={"method"="POST", "path"="/login"}
 *      },
 *      itemOperations={}
 *  )
 */
class Login
{
    /**
     * @var string
     * @ApiProperty(
     *     attributes={
     *         "swagger_context"={
     *             "readOnly"=false,
     *             "required"=true
     *         }
     *     })
     */
    private $email;

    /**
     * @var string
     * @ApiProperty(
     *     attributes={
     *         "swagger_context"={
     *             "readOnly"=false,
     *             "required"=true
     *         }
     *     })
     */
    private $password;

    /**
     * @param string $email
     * @param string $password
     */
    public function __construct(string $email, string $password)
    {
        $this->email = $email;
        $this->password = $password;
    }

    /**
     * @return string
     * @ApiProperty()
     */
    public function getEmail(): string
    {
        return $this->email;
    }

    public function getPassword(): string
    {
        return $this->password;
    }
}
```
In documentation now we have something like that
<img width="758" alt="zrzut ekranu 2018-07-28 o 06 41 33" src="https://user-images.githubusercontent.com/6128834/43353167-897d7490-9231-11e8-8169-9898e4792c8d.png">

In my opinion, documentation should look more like that

<img width="834" alt="zrzut ekranu 2018-07-28 o 06 51 57" src="https://user-images.githubusercontent.com/6128834/43353216-d191c852-9232-11e8-955c-cd157f682d1b.png">

it is easy to achieve just a small modification in `ApiPlatform\Core\Swagger\Serializer\DocumentationNormalizer` metchod `getPropertySchema` 
we need to check if this data is allready set 
```
 private function getPropertySchema(PropertyMetadata $propertyMetadata, \ArrayObject $definitions, array $serializerContext = null): \ArrayObject
  {
        $propertySchema = new \ArrayObject($propertyMetadata->getAttributes()['swagger_context'] ?? []);

        if (!isset($propertySchema['readOnly']) && false === $propertyMetadata->isWritable()) {
            $propertySchema['readOnly'] = true;
        }

        if (isset($propertySchema['description']) && null !== $description = $propertyMetadata->getDescription()) {
            $propertySchema['description'] = $description;
        }
...
```
what do you think about that?

**Comment by ragboyjr** [comment]
@piotrbrzezina This is addressed with #2170

**Comment by alanpoulain** [comment]
Should be fixed.

**Comment by gnumoksha** [comment]
Putting `readOnly: false` in the yaml does not work.

**Comment by christophercolumbusdog** [comment]
Like @gnumoksha pointed out, it seems that it won't work if there are no setters. I have an immutable object that can be constructed through a constructor, but does not have settings. However, it still isn't "readonly", as you can still create the object with all fields.
