### ISSUE TITLE
FilterEagerLoadingExtension skips some entity aliases replacements

### ISSUE THREAD

**Issue by alexbusu** [api-platform/core#4786]
The problem is with the `FilterEagerLoadingExtension::getQueryBuilderWithNewAliases()` method, and it lies in the assumption that the entity alias is always used in the form of `aliasName.fieldName` (alias + `dot` + something), as seen here https://github.com/api-platform/core/blob/ff3aab5b196709c721960c0bb4f1d52759af737d/src/Bridge/Doctrine/Orm/Extension/FilterEagerLoadingExtension.php#L149

The first time I encountered this issue was when I performed some joins with sub-resources, with `relatedEntityAlias.contact = contactAlias`. In this case, the `relatedEntityAlias` was replaced with the new alias, whereas `contactAlias` wasn't, resulting in SQL query error. (I was able to workaround this issue by using `IDENTITY(relatedEntityAlias.contact) = contactAlias.id` in the join condition.)

The second time was when I had to include a many-to-many relationship join, where the condition would be `contactAlias MEMBER OF tagAlias.contacts`. As in the previous case, the `contactAlias` was the one that wasn't replaced in the subquery. It was hard to find a workaround in this case, ending by introducing another join, that has a relationship with the contact and the root entity, resulting in a join condition like `anotherJoinAlias.contact MEMBER OF tagAlias.contacts` - a pretty ugly solution, not to mention the performance impact.

Now, having this problem, I propose a solution. If I don't lack more context, we can improve the alias replacing logic, by using `preg_replace()` instead of `str_replace()`, like this https://3v4l.org/Y0qA6 
Possible fix for #4127 and #2580.

Is it that simple as it looks like? :)

**Comment by alanpoulain** [comment]
It has been resolved by https://github.com/api-platform/core/pull/4592, doesn't it?

**Comment by alexbusu** [comment]
I don't think so.
The intended fix seems to not cover the use cases exposed in this thread. See the current pattern composition in the 2.6 branch: https://github.com/api-platform/core/blob/ffda414da9fd025b360fd7d5a5864fef6b5b9729/src/Bridge/Doctrine/Orm/Extension/FilterEagerLoadingExtension.php#L176 where the ending point is still present.

**Comment by alexbusu** [comment]
My bad. Indeed, the pattern is built without the trailing dot. So that PR should fix the current issue. Thanks!
(I'm still wondering if a word boundary match `\b` would be better at the end of the alias; I hope not)
