### ISSUE TITLE
[JsonSchema] v3.1.6 regression - modifying `output` to a DTO can cause infinite loop in schema types

### ISSUE THREAD

**Issue by jamesisaac** [api-platform/core#5626]
**API Platform version(s) affected**: 3.1.6 up to latest

**Description**

v3.1.6 has introduced an issue in how references in the JsonSchema are calculated, which can lead to incorrect types in the OpenApi schema (and ultimately an infinite loop of types).

- For one of the GET operations of my resource (`GET /greetings/1`), I want the output to be represented as a DTO which contains the resource itself, and some additional fields, so I set `output: GreetingOverviewDto::class` on the Operation.
- Starting in v3.1.6, the type given for the `$greeting` field in the OpenApi docs is incorrect - the schema states that its type is `GreetingOverviewDto` when it should be `Greeting`
- So as well as being incorrect type, it results in an infinite loop when trying to analyse the types, as it's referencing itself.

**How to reproduce**  

I've created a minimal repro here: https://github.com/jamesisaac/apip-3.1.6-bug-jsonschema

Open up http://localhost:8000/docs.json and look at the following location in the json:

```
paths:
  /greetings/{id}:
    get:
      responses:
        200:
          content:
            application/ld+json
              schema:
                $ref: "#/components/schemas/Greeting.GreetingOverviewDto.jsonld-Advanced"

components:
  schemas:
    Greeting.GreetingOverviewDto.jsonld-Advanced:
      properties:
        greeting:
          $ref: "#/components/schemas/Greeting.GreetingOverviewDto.jsonld-Advanced"
```

The above is self-referencing back to the DTO.

Downgrade to 3.1.5 and it works correctly:

```
$ref: "#/components/schemas/Greeting.jsonld-Advanced"
```

**Possible Solution**  

Specifically, this PR seems to have introduced the issue: https://github.com/api-platform/core/pull/5469

By reverting the changes to `SchemaFactory`, it starts working again.

**Comment by sergiuionescu** [comment]
Although I tend to agree with @jamesisaac and the straightforward solution here would be a revert, I've added a [PR](https://github.com/api-platform/core/pull/5973) with a patch that allows DTO wrappers to properly resolve the documentation when the wrapped class ApiResource does not have a custom shortName.

I believe that the question here is if we want the documentation to follow ApiResource definition as opposed to just serialisation groups when nesting ApiResources or Dtos with ApiResources.

Anyway @soyuka please take a look at the new test case and the fix and let me know if you think this can be a good compromise.

PS - there is a failing PHPUnit test that i will further investigate we consider this to be in the right direction.

**Comment by jamesisaac** [comment]
@soyuka @sergiuionescu I believe this issue was fixed with your PR (sorry I forgot to close this original issue).

However, unfortunately it looks like it's regressed again with v4.2.

- `api-platform/json-schema v4.1.28` - Handles self-referencing DTOs properly
- `api-platform/json-schema v4.2.3` - Back to the infinite loop issue

I haven't been able to narrow it down to an exact commit, as between those version I'm having some dependency conflict issues.

**Comment by jamesisaac** [comment]
I suppose this is probably the breaking commit: 79edced67ccca1a7b80455dd94203501d9c4fa89

**Comment by soyuka** [comment]
I could not reproduce, do you have a way to reproduce this on 4.2? I tried what you said and the DTO is correctly handled with a $ref.

**Comment by soyuka** [comment]
I've pushed my branch so you can check

**Comment by jamesisaac** [comment]
Thanks for looking into it @soyuka , I'm hoping to get the time to verify a minimal repro on v4.2 in the next few days, and will compare with your branch to see if I can see the difference.  Will post here once I have it.

**Comment by sergiuionescu** [comment]
@jamesisaac The test added for this case is still in 4.2 https://github.com/api-platform/core/blob/4.2/tests/Functional/OpenApiTest.php#L541 , so technically this should validate that the original fix is still working.

Maybe you are seeing a different edge case?

**Comment by shahzaibm10c** [comment]
Hi, @soyuka @sergiuionescu 

I tried reproducing this issue on API Platform 4.2 using the same wrapper-DTO pattern, and I can confirm the issue still exists for me.

Steps to reproduce

1. Create a resource that uses the DTO as its output:
 ```

<?php

#[ApiResource(
    normalizationContext: ['groups' => ['Simple']],
    operations: [
        new Get(
            output: GreetingOverviewDto::class,
            normalizationContext: ['groups' => ['Advanced']],
        ),
        new Post(),
    ],
)]
class Greeting
{
    #[Serializer\Groups(['Simple', 'Advanced'])]
    public ?int $id = null;

    /**
     * A nice person.
     */
    #[Assert\NotBlank]
    #[Serializer\Groups(['Simple', 'Advanced'])]
    public string $name = '';
}
```

2. Create an output DTO that wraps the resource:

```
#[ApiResource(
    operations: [
        new Get(controller: NotFoundAction::class, read: false, output: false),
    ],
)]
class GreetingOverviewDto
{
    public function __construct(
        #[Serializer\Groups(['Advanced'])]
        public Greeting $greeting,

        #[Serializer\Groups(['Advanced'])]
        public int $viewCount,
    ) {
    }
}
```

3. Open the OpenAPI docs (/docs or /docs.jsonopenapi).
4. Inspect the schema for `Greeting.GreetingOverviewDto(.jsonld)-Advanced.`

Expected result
The greeting property should reference the Greeting schema, not the DTO.

Actual result 
The greeting property inside GreetingOverviewDto references the DTO schema itself, see attached screenshots


<img width="1370" height="628" alt="Image" src="https://github.com/user-attachments/assets/001df449-e10f-4991-8ece-1734b0d9476f" />


<img width="1410" height="406" alt="Image" src="https://github.com/user-attachments/assets/f5f69b56-cfb6-4917-bdd2-f6a81a8d41eb" />

**Comment by shahzaibm10c** [comment]
I’ve created a minimal reproduction repository here:
https://github.com/shahzaibm10c/apip4.2-schema-bug

Cloning the repo and opening `/api/docs` shows that `GreetingOverviewDto.greeting` references the DTO schema itself instead of `Greeting`.

Edited: I also added a test [here](https://github.com/shahzaibm10c/apip4.2-schema-bug/blob/1872aa53becc0c6934db12ab7063c75c66d2cd94/tests/OpenApiDtoWrapperTest.php#L11). The assertion pattern is the same as the core test (wrapper property $ref), but in my case the generated schema is wrong: 

	•	Expected (correct): greeting -> Greeting...
	•	Actual (bug): greeting -> GreetingOverviewDto...

**Comment by soyuka** [comment]
Thank you for the detailed report. However, after reviewing this behavior, this is actually working as designed in API Platform's schema generation system.

When you define:
```php
#[ApiResource(
    operations: [
        new Get(output: GreetingOverviewDto::class),
    ],
)]
class Greeting
```

You're declaring that the API representation of `Greeting` is `GreetingOverviewDto`. API Platform generates schemas based on **how resources are exposed through operations**, not just their PHP class types.

When `GreetingOverviewDto` contains:
```php
public Greeting $greeting;
```

The schema generator looks at how `Greeting` is represented in the API (via its GET operation), which is `GreetingOverviewDto`. This results in:
```json
{
  "$ref": "#/definitions/Greeting.GreetingOverviewDto.jsonld-Advanced"
}
```

JSON Schema explicitly supports recursive references using `$ref`. This is not an "infinite loop" - it's a recursive structure that schema consumers (like OpenAPI validators, code generators, etc.) are designed to handle.

For example, this is valid and common in APIs representing tree structures, linked lists, or as in your case, wrapped resources.

If you want the `greeting` property to reference the "unwrapped" `Greeting` data structure, you should **use separate classes**:

```php
// Raw data class (no operations)
class GreetingData {
    public int $id;
    public string $name;
}

// DTO that wraps the data
class GreetingOverviewDto {
    public GreetingData $greeting;  // ← Now references GreetingData, not Greeting resource
    public int $viewCount;
}

// Resource uses the DTO as output
#[ApiResource(operations: [
    new Get(output: GreetingOverviewDto::class),
])]
class Greeting {
    // ...
}
```

This way, `GreetingData` has no API operations, so it will be serialized as its own schema definition without the DTO wrapper.

If this doesn't fit your use case, the solution is to restructure your classes to separate data models from resource representations.
