### ISSUE TITLE
Laravel - Serialization not working on relations with a CamelCase name

### ISSUE THREAD

**Issue by Lurivar** [api-platform/core#7344]
**API Platform version(s) affected**: 4.1.20

**Description**  
In Laravel, relations whose names are in camelCase will not serialize properly.

**How to reproduce**  
```
#[ApiResource(
    normalizationContext: ['groups' => ['proof:read']],
    denormalizationContext: ['groups' => ['proof:write']],
    middleware: ['auth:sanctum', AuthorizeOwnResourceAccess::class],
    operations: [
        new Post(
            middleware: ['auth:sanctum', AuthorizeOwnResourceAccess::class]
        ),
        new Get(),
        new GetCollection(),
        new Patch(),
        new Delete(),
        new Put(),
    ]
)]
#[Groups(['proof:read', 'proof:write'])]
class Proof extends Model
{
    public function test(): BelongsTo
    {
        return $this->belongsTo(ProofStatusMessage::class, 'proof_status_message_id');
    }
    public function test2(): BelongsTo
    {
        return $this->belongsTo(ProofStatusMessage::class, 'proof_status_message_id');
    }
    public function testTruc(): BelongsTo
    {
        return $this->belongsTo(ProofStatusMessage::class, 'proof_status_message_id');
    }
    public function testTruc2(): BelongsTo
    {
        return $this->belongsTo(ProofStatusMessage::class, 'proof_status_message_id');
    }
    public function statusMessage(): BelongsTo
    {
        return $this->belongsTo(ProofStatusMessage::class, 'proof_status_message_id');
    }
}

---------

#[ApiResource(
    normalizationContext: ['groups' => ['proofStatusMessage:read']],
    denormalizationContext: ['groups' => ['proofStatusMessage:write']],
    middleware: ['auth:sanctum', AuthorizeOwnResourceAccess::class]
)]
#[ApiProperty(property: 'id', serialize: new Groups(['proof:read']))]
#[ApiProperty(property: 'label', serialize: new Groups(['proof:read']))]
#[ApiProperty(property: 'content', serialize: new Groups(['proof:read']))]
#[Groups(['proofStatusMessage:read', 'proofStatusMessage:write'])]
class ProofStatusMessage extends Model
{
}
```

In this example, only the relations named test and test2 will be correctly serialized. The other ones won't appear at all unless adding them in an ApiProperty attribute this way `#[ApiProperty(property: 'proofType', serialize: new Groups(['proof:read']))]` but even then only the id will be serialized, the label and content will never show up.

**Possible Solution**  

**Additional Context**  
Edit : To add to this, it also works when using snake_case instead of camelCase for the name, and it's returned as camelCase in the json anyway.

Eg : 
```
    // This works
    public function status_message(): BelongsTo
    {
        return $this->belongsTo(ProofStatusMessage::class, 'proof_status_message_id');
    }

    // This does not work
    public function statusMessage(): BelongsTo
    {
        return $this->belongsTo(ProofStatusMessage::class, 'proof_status_message_id');
    }
```

**Comment by soyuka** [comment]
Hopefully also fixed by #7316

**Comment by Lurivar** [comment]
Still bugged as of 4.1.21

Edit: Actually, this is unclear, I need to test it more because I got confusing results in different models.

**Comment by shahzaibtariqbutt** [comment]
This is not fixed, I am still facing this issue in 4.1.21.

```
In Slot.php its working but I have to do something like this
#[ApiProperty(
    property: 'area',
    writableLink: true,
    readable: true,
    writable: true, // important to write relations
    serialize: new Groups(
        ['Slot:W']
    )
)]

But in Order.php its not as the relation is in camelCase.
#[ApiProperty(
    writableLink: true,
    readable: true,
    writable: true, // important to write relations
    serialize: new Groups([
        'Order:W'
    ]),
    property: 'dropoffSlot',
)]

    /**
     * Dropoff slot relation.
     *
     * @return BelongsTo<Slot, $this>
     */
    public function dropoffSlot(): BelongsTo
    {
        return $this->belongsTo(Slot::class, 'dropoff_slot_id');
    }
```

**Comment by soyuka** [comment]
Did you clear the cache? Since https://github.com/api-platform/core/pull/7332 `writable` is provided by the serialization metadata. You have the default configuration? I'll add a new test asap.

**Comment by Lurivar** [comment]
I can confirm I also still have the problem. I was confused because I had a mix of camel and snake case relations until the bug is fixed, with different serialization groups.
I also have cleared the cache (well unless you mean one specific to ApiPlatform I don't know about)

**Comment by soyuka** [comment]
Hi I'm not able to reproduce: 
Model:

```php
<?php

declare(strict_types=1);

namespace Workbench\App\Models;

use ApiPlatform\Metadata\ApiProperty;
use ApiPlatform\Metadata\ApiResource;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Relations\BelongsTo;
use Symfony\Component\Serializer\Attribute\Groups;

#[ApiResource(normalizationContext: ['groups' => ['read']])]
#[ApiProperty(property: 'name', serialize: [new Groups(['read'])])]
#[ApiProperty(property: 'relatedAuthor', serialize: [new Groups(['read'])])]
class CamelCaseRelationTest extends Model
{
    use HasFactory;

    protected $table = 'camel_case_relation_tests';
    protected $fillable = ['name'];

    public function relatedAuthor(): BelongsTo
    {
        return $this->belongsTo(Author::class, 'related_author_id');
    }
}
```

Test:

```php
        public function testCamelCaseRelationSerialization(): void
    {
        $camelCaseRelationTest = CamelCaseRelationTestFactory::new()->create();
        $response = $this->get($this->getIriFromResource($camelCaseRelationTest), ['accept' => 'application/ld+json']);
        $response->assertStatus(200);
        $response->assertJsonFragment([
            '@context' => '/api/contexts/CamelCaseRelationTest',
            '@id' => $this->getIriFromResource($camelCaseRelationTest),
            '@type' => 'CamelCaseRelationTest',
            'name' => $camelCaseRelationTest->name,
        ]);
        $this->assertArrayHasKey('relatedAuthor', $response->json());
        $this->assertArrayHasKey('@id', $response->json('relatedAuthor'));
        $this->assertEquals($this->getIriFromResource($camelCaseRelationTest->relatedAuthor), $response->json('relatedAuthor.@id'));
    }

```

Please provide a reproducer.

**Comment by shahzaibtariqbutt** [comment]
@soyuka Hi thanks for your response

Here is my usecase, I have not tried the get operation so not sure about that, but for post:

Order.php
```
#[ApiResource(
    operations: [
        new Post(
            rules: OrderPostRequest::class,
            processor: OrderCreateProcessor::class,
            normalizationContext: [
                'groups' => [
                    'read',
                ]
            ],
            denormalizationContext: [
                'groups' => [
                    'write',
                ]
            ]
        ),
    ]
);

class Order extends Model
{
    public function pickup_slot(): BelongsTo
    {
        return $this->belongsTo(Slot::class, 'pickup_slot_id');
    }
}
```

Processor
```
public function process(mixed $data, Operation $operation, array $uriVariables = [], array $context = []): Order
    {
        $order = $this->persistProcessor->process($data, $operation, $uriVariables, $context);
        Assert::isInstanceOf($order, Order::class);
        $order = $order->refresh();

        $this->sendEmail($order);
        $this->considerCreatingRecurring($order);

        return $order;
    }
```

Test will pass when relation is snake_case but will fail when its camelCase
```
public function testCreateOrder(): void
    {
        $pickupDate = '2024-10-24';
        $dropoffDate = '2024-10-25';

        $pickupWeekday = Carbon::parse($pickupDate)->weekday();
        $dropoffWeekday = Carbon::parse($dropoffDate)->weekday();

        $pickupSlot = Slot::factory()->create(['week_day' => $pickupWeekday, 'is_active' => true]);
        $dropoffSlot = Slot::factory()->create(['week_day' => $dropoffWeekday, 'is_active' => true]);

        $response = $this->request('POST', '/orders', [
            'pickupDate' => $pickupDate,
            'pickupSlot' => "/slots/{$pickupSlot->id}",
            'dropoffDate' => $dropoffDate,
            'dropoffSlot' => "/slots/{$dropoffSlot->id}",
            'note' => 'this is test note.',
        ]);

        $response->assertStatus(201);
        $response->assertJson([
            'pickupDate' => $pickupDate . 'T00:00:00+00:00',
            'dropoffDate' => $dropoffDate . 'T00:00:00+00:00',
            'pickupSlot' => [
                '@id' => "/slots/{$pickupSlot->id}",
                '@type' => 'Slot',
                'startTime' => $pickupSlot->start_time,
                'endTime' => $pickupSlot->end_time,
                'weekDay' => $pickupSlot->week_day,
            ],
            'dropoffSlot' => [
                '@id' => "/slots/{$dropoffSlot->id}",
                '@type' => 'Slot',
                'startTime' => $dropoffSlot->start_time,
                'endTime' => $dropoffSlot->end_time,
                'weekDay' => $dropoffSlot->week_day,
            ],
            'note' => 'this is test note.',
        ]);


        Mail::assertQueued(OrderCreatedMail::class, function (OrderCreatedMail $mail) {
            $user = \user();
            return $mail->hasTo($user->email);
        });
    }
```

And I believe we dont need `$fillable` when we are writing with apip?
